// config.js — datos de dominio: etiquetas, moods, géneros, plantillas, famosos, IA, sinónimos
window.VATE = window.VATE || {};
VATE.config = (function () {
  const TAGS = {
    'Intro':      { color:'#64b5f6', hint:'Atmósfera inicial: describe el paisaje sonoro…' },
    'Verse':      { color:'#81c784', hint:'Cuenta la historia… 4 líneas con rima funcionan bien' },
    'Pre-Chorus': { color:'#ffd54f', hint:'Sube la tensión antes del estribillo…' },
    'Chorus':     { color:'#ff8a65', hint:'El gancho: repetible, emocional, cantable…' },
    'Hook':       { color:'#f06292', hint:'Frase gancho corta y obsesiva…' },
    'Bridge':     { color:'#ba68c8', hint:'Giro emocional: otra perspectiva…' },
    'Refrain':    { color:'#ffab91', hint:'Estribillo breve que retorna…' },
    'Interlude':  { color:'#90a4ae', hint:'(sección instrumental)' },
    'Solo':       { color:'#e57373', hint:'(solo instrumental)' },
    'Breakdown':  { color:'#7986cb', hint:'Caída de energía, ritmo roto…' },
    'Ad-libs':    { color:'#4dd0e1', hint:'(yeah, eh, suspiros…)' },
    'Outro':      { color:'#a1887f', hint:'Despedida: eco del tema principal…' }
  };
  const MOODS = [
    { id:'alegre',      label:'😊 Alegre',      color:'#f7b32b', val:6 },
    { id:'energico',    label:'⚡ Enérgico',    color:'#ef476f', val:7 },
    { id:'romantico',   label:'💗 Romántico',   color:'#ff7b9c', val:5 },
    { id:'esperanzador',label:'🌅 Esperanzador',color:'#2ec4b6', val:6 },
    { id:'nostalgico',  label:'🕰 Nostálgico',  color:'#b08968', val:3 },
    { id:'triste',      label:'🌧 Triste',      color:'#4c6ef5', val:2 },
    { id:'oscuro',      label:'🌑 Oscuro',      color:'#6c5ce7', val:1 },
    { id:'neutral',     label:'◽ Neutral',     color:'#8d99ae', val:4 }
  ];
  const moodColor = id => (MOODS.find(m => m.id === id) || MOODS[7]).color;
  const moodVal   = id => (MOODS.find(m => m.id === id) || MOODS[7]).val;
  const DYNAMICS = ['pp','p','mp','mf','f','ff'];
  const CUES = ['whispered','belted','spoken','soft','shouted','ad-lib','harmonies','falsetto'];

  const GENRES = {
    pop:       { name:'Pop',            bpm:[100,122], style:'pop melódico moderno, sintes brillantes' },
    balada:    { name:'Balada',         bpm:[62,76],   style:'balada íntima, piano y cuerdas' },
    reggaeton: { name:'Reggaetón',      bpm:[88,96],   style:'reggaetón, dembow, bajo 808' },
    trap:      { name:'Trap Latino',    bpm:[130,150], style:'trap latino, hi-hats rápidos, 808' },
    rap:       { name:'Rap',            bpm:[85,95],   style:'rap conciencia, boom bap' },
    rock:      { name:'Rock',           bpm:[112,140], style:'rock alternativo, guitarras' },
    corrido:   { name:'Corrido Tumbado',bpm:[108,126], style:'corrido tumbado, requinto y tololoche' },
    cumbia:    { name:'Cumbia',         bpm:[92,110],  style:'cumbia tropical, güiro y acordeón' },
    indie:     { name:'Indie Folk',     bpm:[72,90],   style:'indie folk íntimo, guitarra acústica' },
    rnb:       { name:'R&B',            bpm:[66,84],   style:'R&B nocturno, neosoul' },
    edm:       { name:'EDM',            bpm:[124,132], style:'EDM festival, build y drop' },
    metal:     { name:'Metal',          bpm:[140,175], style:'metal épico, doble bombo' },
    bolero:    { name:'Bolero',         bpm:[60,72],   style:'bolero clásico, trío de guitarras' },
    flamenco:  { name:'Flamenco Urbano',bpm:[90,108],  style:'flamenco urbano, palmas y 808' }
  };
  const INSTR = {
    Intro:'piano suave / pads atmosféricos', Verse:'bajo + batería contenida, arpegio',
    'Pre-Chorus':'riser, palmas, sube filtros', Chorus:'full mix: batería, bajo, sintes',
    Hook:'808 + voz doblada', Bridge:'solo piano/cuerdas, silencio de batería',
    Outro:'eco del intro, fade', Solo:'guitarra/sinte protagonista', Breakdown:'mitad de tempo, sub-bass',
    Refrain:'acústico + voz', Interlude:'instrumental temático', 'Ad-libs':'voz + fx'
  };

  const sec = (tag, meta, mood, dyn, instruments) => ({ tag, meta, mood, dyn, instruments });
  const TEMPLATES = [
    { id:'pop2026', name:'Pop Himno 2026', genre:'pop', sections:[
      sec('Intro','pads brillantes, arpegio','esperanzador','mp',INSTR.Intro),
      sec('Verse','voz cercana, bajo suave','nostalgico','mf',INSTR.Verse),
      sec('Pre-Chorus','riser, palmas','energico','mf',INSTR['Pre-Chorus']),
      sec('Chorus','full mix, belted','alegre','f',INSTR.Chorus),
      sec('Verse','añade guitarra','nostalgico','mf',INSTR.Verse),
      sec('Pre-Chorus','más capas','energico','f',INSTR['Pre-Chorus']),
      sec('Chorus','full mix','alegre','ff',INSTR.Chorus),
      sec('Bridge','solo piano','triste','p',INSTR.Bridge),
      sec('Chorus','modulación + ad-libs','alegre','ff',INSTR.Chorus),
      sec('Outro','fade, eco vocal','esperanzador','mp',INSTR.Outro)]},
    { id:'balada', name:'Balada Íntima', genre:'balada', sections:[
      sec('Intro','piano solo','nostalgico','p',INSTR.Intro),
      sec('Verse','voz susurrada','triste','p',INSTR.Verse),
      sec('Chorus','entran cuerdas','romantico','mf',INSTR.Chorus),
      sec('Verse','chelo contrapunto','nostalgico','mp',INSTR.Verse),
      sec('Chorus','batería suave','romantico','f',INSTR.Chorus),
      sec('Bridge','clímax, belted','triste','ff',INSTR.Bridge),
      sec('Chorus','a cappella inicio','romantico','f',INSTR.Chorus),
      sec('Outro','piano, nota larga','nostalgico','pp',INSTR.Outro)]},
    { id:'perreo', name:'Reggaetón Perreo', genre:'reggaeton', sections:[
      sec('Intro','dembow entra, tag del producer','energico','mf',INSTR.Intro),
      sec('Verse','flow relajado','alegre','mf',INSTR.Verse),
      sec('Pre-Chorus','sube con synth','energico','f',INSTR['Pre-Chorus']),
      sec('Chorus','perreo full, 808','energico','ff',INSTR.Chorus),
      sec('Verse','doble tempo','alegre','f',INSTR.Verse),
      sec('Chorus','repetir gancho','energico','ff',INSTR.Chorus),
      sec('Breakdown','medio tiempo, sensual','romantico','mf',INSTR.Breakdown),
      sec('Chorus','con ad-libs','energico','ff',INSTR.Chorus),
      sec('Outro','fade con dembow','alegre','mp',INSTR.Outro)]},
    { id:'trap', name:'Trap Latino', genre:'trap', sections:[
      sec('Intro','atmósfera oscura, 808','oscuro','mp',INSTR.Intro),
      sec('Hook','autotune, repetitivo','oscuro','f',INSTR.Hook),
      sec('Verse','hi-hats rápidos','oscuro','mf',INSTR.Verse),
      sec('Hook','doblado','oscuro','ff',INSTR.Hook),
      sec('Verse','flow picado','energico','f',INSTR.Verse),
      sec('Hook','+ ad-libs','oscuro','ff',INSTR.Hook),
      sec('Outro','chopped & screwed','oscuro','p',INSTR.Outro)]},
    { id:'rap', name:'Rap Conciencia', genre:'rap', sections:[
      sec('Intro','scratch, vinilo','nostalgico','mp',INSTR.Intro),
      sec('Verse','boom bap clásico','oscuro','mf',INSTR.Verse),
      sec('Chorus','coro con gancho','energico','f',INSTR.Chorus),
      sec('Verse','sube intensidad','oscuro','f',INSTR.Verse),
      sec('Chorus','repetir','energico','f',INSTR.Chorus),
      sec('Verse','verso final, spoken','nostalgico','mf',INSTR.Verse),
      sec('Outro','mensaje hablado','neutral','p',INSTR.Outro)]},
    { id:'rock', name:'Rock Alternativo', genre:'rock', sections:[
      sec('Intro','riff de guitarra','energico','mf',INSTR.Intro),
      sec('Verse','bajo protagonista','oscuro','mf',INSTR.Verse),
      sec('Chorus','distorsión full','energico','ff',INSTR.Chorus),
      sec('Verse','mitad de energía','oscuro','mf',INSTR.Verse),
      sec('Chorus','full','energico','ff',INSTR.Chorus),
      sec('Solo','guitarra con wah','energico','f',INSTR.Solo),
      sec('Bridge','limpio, susurrado','triste','p',INSTR.Bridge),
      sec('Chorus','explosión final','energico','ff',INSTR.Chorus),
      sec('Outro','feedback, fade','oscuro','mf',INSTR.Outro)]},
    { id:'corrido', name:'Corrido Tumbado', genre:'corrido', sections:[
      sec('Intro','requinto brillante','alegre','mf',INSTR.Intro),
      sec('Verse','tololoche marcando','nostalgico','mf',INSTR.Verse),
      sec('Verse','segunda vuelta','nostalgico','mf',INSTR.Verse),
      sec('Chorus','corrido full','alegre','f',INSTR.Chorus),
      sec('Verse','historia continúa','nostalgico','mf',INSTR.Verse),
      sec('Chorus','repetir','alegre','f',INSTR.Chorus),
      sec('Outro','requinto final','alegre','mp',INSTR.Outro)]},
    { id:'cumbia', name:'Cumbia Tropical', genre:'cumbia', sections:[
      sec('Intro','acordeón + güiro','alegre','mf',INSTR.Intro),
      sec('Verse','ritmo marcado','alegre','mf',INSTR.Verse),
      sec('Chorus','coro bailable','alegre','f',INSTR.Chorus),
      sec('Verse','vuelve acordeón','alegre','mf',INSTR.Verse),
      sec('Chorus','repetir','alegre','f',INSTR.Chorus),
      sec('Interlude','solo de acordeón','alegre','mf',INSTR.Interlude),
      sec('Chorus','con coros','alegre','ff',INSTR.Chorus),
      sec('Outro','despedida bailable','alegre','mp',INSTR.Outro)]},
    { id:'indie', name:'Indie Folk', genre:'indie', sections:[
      sec('Intro','guitarra acústica fingerpicking','nostalgico','p',INSTR.Intro),
      sec('Verse','voz íntima','nostalgico','mp',INSTR.Verse),
      sec('Chorus','entran armonías','esperanzador','mf',INSTR.Chorus),
      sec('Verse','añade percusión suave','nostalgico','mp',INSTR.Verse),
      sec('Chorus','más voces','esperanzador','f',INSTR.Chorus),
      sec('Bridge','silencio + voz','triste','p',INSTR.Bridge),
      sec('Chorus','todos los instrumentos','esperanzador','f',INSTR.Chorus),
      sec('Outro','acústica se apaga','nostalgico','pp',INSTR.Outro)]},
    { id:'rnb', name:'R&B Nocturno', genre:'rnb', sections:[
      sec('Intro','rhodes + lluvia','oscuro','p',INSTR.Intro),
      sec('Verse','voz sedosa, spoken-sung','romantico','mp',INSTR.Verse),
      sec('Pre-Chorus','falsetto','romantico','mf',INSTR['Pre-Chorus']),
      sec('Chorus','groove completo','romantico','f',INSTR.Chorus),
      sec('Verse','bajo profundo','oscuro','mf',INSTR.Verse),
      sec('Chorus','+ armonías','romantico','f',INSTR.Chorus),
      sec('Bridge','modulación jazzy','nostalgico','mf',INSTR.Bridge),
      sec('Chorus','vocal run final','romantico','ff',INSTR.Chorus)]},
    { id:'edm', name:'EDM Festival', genre:'edm', sections:[
      sec('Intro','atmósfera progresiva','esperanzador','mp',INSTR.Intro),
      sec('Verse','vocal chop, piano','alegre','mf',INSTR.Verse),
      sec('Pre-Chorus','build + riser','energico','f',INSTR['Pre-Chorus']),
      sec('Chorus','DROP, synth lead','energico','ff',INSTR.Chorus),
      sec('Verse','baja energía','alegre','mf',INSTR.Verse),
      sec('Pre-Chorus','build doble','energico','f',INSTR['Pre-Chorus']),
      sec('Chorus','DROP 2','energico','ff',INSTR.Chorus),
      sec('Breakdown','piano + voz sola','nostalgico','p',INSTR.Breakdown),
      sec('Chorus','drop final + confeti','energico','ff',INSTR.Chorus),
      sec('Outro','DJ friendly, fade','esperanzador','mp',INSTR.Outro)]},
    { id:'metal', name:'Metal Épico', genre:'metal', sections:[
      sec('Intro','riff pesado, doble bombo','oscuro','f',INSTR.Intro),
      sec('Verse','palm mute','oscuro','f',INSTR.Verse),
      sec('Chorus','melódico, power chords','energico','ff',INSTR.Chorus),
      sec('Verse','bajo + batería','oscuro','f',INSTR.Verse),
      sec('Chorus','repetir','energico','ff',INSTR.Chorus),
      sec('Breakdown','mitad de tempo, gutural','oscuro','ff',INSTR.Breakdown),
      sec('Solo','shred','energico','f',INSTR.Solo),
      sec('Chorus','coro épico','energico','ff',INSTR.Chorus),
      sec('Outro','riff final, campana','oscuro','f',INSTR.Outro)]},
    { id:'bolero', name:'Bolero Clásico', genre:'bolero', sections:[
      sec('Intro','trío de guitarras','romantico','mp',INSTR.Intro),
      sec('Verse','voz cálida','romantico','mf',INSTR.Verse),
      sec('Verse','segunda estrofa','romantico','mf',INSTR.Verse),
      sec('Chorus','armonía de trío','romantico','f',INSTR.Chorus),
      sec('Verse','puente hablado','nostalgico','mp',INSTR.Verse),
      sec('Chorus','sube medio tono','romantico','f',INSTR.Chorus),
      sec('Outro','ritardando, abrazo final','romantico','pp',INSTR.Outro)]},
    { id:'flamenco', name:'Flamenco Urbano', genre:'flamenco', sections:[
      sec('Intro','palmas + guitarra flamenca','oscuro','mp',INSTR.Intro),
      sec('Verse','cante quejío suave','triste','mf',INSTR.Verse),
      sec('Pre-Chorus','entra 808','energico','f',INSTR['Pre-Chorus']),
      sec('Chorus','urbano + palmas','energico','ff',INSTR.Chorus),
      sec('Verse','verso rapeado','oscuro','mf',INSTR.Verse),
      sec('Chorus','repetir','energico','ff',INSTR.Chorus),
      sec('Bridge','guitarra sola, falseta','triste','p',INSTR.Bridge),
      sec('Chorus','fin de fiesta','energico','ff',INSTR.Chorus),
      sec('Outro','palmas se apagan','nostalgico','mp',INSTR.Outro)]}
  ];

  const FAMOUS = [
    { t:'Blinding Lights', a:'The Weeknd', g:'Synthpop', s:['Intro','Verse','Chorus','Verse','Chorus','Bridge','Chorus','Outro'] },
    { t:'Shape of You', a:'Ed Sheeran', g:'Pop', s:['Intro','Verse','Chorus','Verse','Chorus','Bridge','Chorus'] },
    { t:'Despacito', a:'Luis Fonsi', g:'Pop urbano', s:['Intro','Verse','Pre-Chorus','Chorus','Verse','Pre-Chorus','Chorus','Bridge','Chorus'] },
    { t:'Gasolina', a:'Daddy Yankee', g:'Reggaetón', s:['Intro','Verse','Chorus','Verse','Chorus','Outro'] },
    { t:'Shallow', a:'Lady Gaga & B. Cooper', g:'Balada', s:['Intro','Verse','Chorus','Verse','Chorus','Bridge','Chorus'] },
    { t:'Pepas', a:'Farruko', g:'EDM latino', s:['Intro','Verse','Chorus','Verse','Chorus','Breakdown','Chorus'] },
    { t:'Hawái', a:'Maluma', g:'Pop urbano', s:['Intro','Verse','Pre-Chorus','Chorus','Verse','Pre-Chorus','Chorus','Outro'] },
    { t:'Lamento Boliviano', a:'Enanitos Verdes', g:'Rock en español', s:['Intro','Verse','Chorus','Verse','Chorus','Bridge','Chorus'] },
    { t:'Tití Me Preguntó', a:'Bad Bunny', g:'Dembow', s:['Intro','Verse','Chorus','Verse','Chorus','Outro'] },
    { t:'Bohemian Rhapsody', a:'Queen', g:'Rock', s:['Intro','Verse','Chorus','Bridge','Solo','Chorus','Outro'] }
  ];

  const INSPIRE = {
    amor:      ['Tu nombre es la canción que no sé terminar','Guardo tu risa en un cajón de luz','Somos dos mitos que se quieren contar','Me aprendí de memoria tu manera de llegar','El amor es un idioma que inventamos tú y yo','Bésame como quien vuelve a casa'],
    desamor:   ['Quedó tu taza llena de silencio','Te fuiste y el reloj se puso de tu lado','Somos la foto que nadie reveló','Aprendí a perder ganando cicatrices','Tu adiós fue un tren que no salió en mi horario','El olvido es un arte que aún no domino'],
    noche:     ['La ciudad se enciende cuando yo me apago','Neón y lluvia, mi alfombra roja','La luna firma el cielo con tinta plateada','Medianoche: el único reloj que respeto','Las luces parpadean en código secreto','La noche es un piano que nadie se atreve a tocar'],
    ciudad:    ['Cristales que reflejan lo que fuimos','El metro lleva sueños en hora punta','Grafitis que confiesan lo que callamos','Esta esquina conoce todos mis finales','Los semáforos deciden hasta el destino','Ruido de claxon, sinfonía de supervivientes'],
    mar:       ['Tu piel tiene mareas que no sé navegar','El mar guarda cartas que nunca envié','Olas que vienen con tu nombre escrito','Sal en la herida, sal en el adiós','La espuma borra huellas, no recuerdos','Faro apagado esperando tu barco'],
    libertad:  ['Rompo el mapa, el norte lo decido yo','Viento en contra: mi combustible','Nací sin jaula, me sobran cielos','Corro más que mi propia sombra','Las rejas eran de papel','Libre como un verso sin puntuación'],
    sueños:    ['Soñé que el tiempo me pedía perdón','Mis sueños pagan renta en mi almohada','Construí castillos con planos de nubes','Despierto para cerrar los ojos mejor','La realidad es un sueño con alarma','Persigo cometas con hilo de fe'],
    fiesta:    ['Hoy el suelo es de quien lo baila','Sube el volumen que se oiga en el barrio','Brindis por los que no están y por los que vienen','La pista es un templo, el DJ mi profeta','Confeti en las venas, hielo en la copa','Que la noche no termine, que empiece']
  };

  const SYNONYMS = [
    'amor|cariño,afecto,pasión,devoción,querer,ternura',
    'corazón|alma,pecho,ser,esencia,sentimiento',
    'alma|espíritu,esencia,ser,interior,ánima',
    'noche|oscuridad,penumbra,medianoche,tinieblas,velada',
    'luz|brillo,resplandor,destello,fulgor,claridad,lumbre',
    'dolor|pena,sufrimiento,agonía,tormento,angustia,herida',
    'fuego|llama,fogata,incendio,brasa,ardor,lumbre',
    'llorar|sollozar,suplicar,gemir,lagrimear,plañir',
    'triste|melancólico,apenado,apesadumbrado,mustio,afligido',
    'alegre|contento,jubiloso,gozoso,radiante,feliz',
    'miedo|temor,pánico,terror,espanto,temblor',
    'soñar|imaginar,fantasear,anhelar,ansiar,desear',
    'caminar|andar,marchar,pasear,recorrer,deambular',
    'correr|sprintar,galopar,volar,apresurarse',
    'mirar|contemplar,observar,admirar,avistar,ojear',
    'ver|contemplar,observar,percibir,distinguir',
    'decir|confesar,susurrar,gritar,contar,narrar',
    'cantar|entonar,vocalizar,tararear,corear',
    'bailar|girar,saltar,moverse,contonearse',
    'besar|acariciar,rozar,saborear',
    'abrazar|estrechar,ceñir,envolver',
    'olvidar|borrar,soltar,superar,dejar',
    'recordar|rememorar,revivir,memorizar,remontar',
    'esperar|aguardar,ansiarse,desear',
    'buscar|rastrear,explorar,perseguir,hallar',
    'encontrar|hallar,topar,descubrir,dar',
    'perder|extraviar,malgastar,desperdiciar',
    'ganar|vencer,triunfar,conquistar,lograr',
    'cielo|firmamento,bóveda,horizonte,altura',
    'estrella|astro,lucero,estela,destello',
    'luna|selene,astro,nocturna,plateada',
    'sol|astro,rey,brillo,amanecer',
    'mar|océano,agua,sal,abisal',
    'río|corriente,cauce,agua,arroyo',
    'viento|brisa,aire,huracán,soplo',
    'lluvia|aguacero,chorro,llovizna,tempestad',
    'flor|rosa,pétalo,jardín,aroma',
    'tiempo|hora,instante,eternidad,segundo',
    'vida|existencia,aliento,destino,jornada',
    'muerte|final,adiós,ocaso,silencio',
    'camino|senda,ruta,rumbo,vereda',
    'casa|hogar,refugio,nido,techo',
    'ciudad|urbe,barrio,calle,asfalto',
    'calle|avenida,esquina,rúa,bulevar',
    'ojos|mirada,pupila,ventana,faro',
    'manos|caricia,tacto,palma,dedos',
    'voz|canto,eco,grito,susurro',
    'palabra|verso,frase,idioma,promesa',
    'silencio|calma,pausa,quietud,ausencia',
    'mentira|engaño,farsa,máscara,ficción',
    'verdad|certeza,realidad,destello',
    'libertad|vuelo,escape,aire,horizonte',
    'cárcel|jaula,prisión,celda,grillete',
    'guerra|batalla,pelea,conflicto,lucha',
    'paz|calma,tregua,serenidad,quietud',
    'fiesta|rumba,celebración,jolgorio,parranda',
    'amigo|hermano,compañero,cómplice,aliado',
    'enemigo|rival,contrario,adversario',
    'rey|monarca,soberano,amo,señor',
    'reina|soberana,monarca,dama',
    'ángel|guardián,celestial,ala',
    'demonio|diablo,sombra,tentación',
    'cielo|paraíso,gloria,edén',
    'infierno|abismo,fuego,caos',
    'oro|tesoro,riqueza,brillo,fortuna',
    'dinero|billete,oro,fortuna,moneda',
    'fiesta|noche,rumba,baile',
    'cuerpo|piel,figura,silueta,carne',
    'piel|tacto,carne,terciopelo',
    'sangre|vena,vida,rojo,fuego',
    'lágrima|llanto,gota,rocío,pena',
    'sonrisa|risa,alegría,gesto,dulzura',
    'herida|cicatriz,marca,dolor,golpe',
    'cicatriz|marca,huella,recuerdo',
    'recuerdo|memoria,huella,eco,imagen',
    'promesa|juramento,pacto,palabra',
    'secreto|confidencia,misterio,silencio',
    'misterio|enigma,secreto,incógnita',
    'destino|suerte,azar,rumbo,fortuna',
    'suerte|azar,fortuna,destino,ventura',
    'batalla|pelea,guerra,combate,lucha',
    'victoria|triunfo,gloria,corona',
    'corona|trono,oro,gloria,reinado',
    'trono|silla,corona,poder,reino',
    'poder|fuerza,mando,imperio,dominio',
    'fuerza|poder,energía,ímpetu,brío',
    'valiente|audaz,osado,heroico,bravo',
    'héroe|campeón,leyenda,ídolo,mito',
    'leyenda|mito,historia,cuento,fábula',
    'historia|cuento,relato,crónica,leyenda',
    'canción|tema,melodía,himno,verso',
    'melodía|ritmo,son,armonía,tune',
    'ritmo|pulso,beat,compás,cadencia',
    'escenario|tarima,tablado,pista,arena',
    'fama|gloria,éxito,estrellato',
    'éxito|triunfo,fama,logro,victoria'
  ];

  const STOPWORDS = new Set(('de la el en y a los se del las un por con no una su para es al lo como más o pero sus le ya que este ha sí porque esta son entre está cuando muy sin sobre también me hasta hay donde quien desde todo nos durante todos uno les ni contra otros ese eso ante ellos e esto mí antes algunos qué unos yo otro otras otra él tanto esa estos mucho quienes nada muchos cual poco ella estar estas algunas algo nosotros mi mis tú te ti tu tus ellas nuestra nuestro sido fue ser soy eres somos tengo tienes tiene tenemos quiero quieres quiere queremos puedo puedes puede podemos voy vas va vamos fui fuiste fue fuimos era eras éramos eran estoy estás estamos están').split(/\s+/));

  return { TAGS, MOODS, moodColor, moodVal, DYNAMICS, CUES, GENRES, INSTR, TEMPLATES, FAMOUS, INSPIRE, SYNONYMS, STOPWORDS };
})();